insert into city (city_id, name) values ('88760', 'Elbasan');
insert into city (city_id, name) values ('49422', 'Sojo');
insert into city (city_id, name) values ('56252', 'Liangzeng');
insert into city (city_id, name) values ('78096', 'Skore');
insert into city (city_id, name) values ('75724', 'Blatná');
insert into city (city_id, name) values ('69229', 'La Cañada');
insert into city (city_id, name) values ('31087', 'Osasco');
insert into city (city_id, name) values ('44359', 'Katoúna');
insert into city (city_id, name) values ('36172', 'Itapeva');
insert into city (city_id, name) values ('19765', 'Bonavista');
insert into city (city_id, name) values ('21784', 'Santa María de Jesús');
insert into city (city_id, name) values ('40509', 'Carrières-sur-Seine');
insert into city (city_id, name) values ('91328', 'Sanjiazi');
insert into city (city_id, name) values ('89649', 'Renchaoxi');
insert into city (city_id, name) values ('73911', 'Kangping');
insert into city (city_id, name) values ('57196', 'Long’anqiao');
insert into city (city_id, name) values ('96497', 'Ambositra');
insert into city (city_id, name) values ('55268', 'Ranambeling');
insert into city (city_id, name) values ('53813', 'Ołpiny');
insert into city (city_id, name) values ('14859', 'Kalianget');
insert into city (city_id, name) values ('55964', 'Hudson');
insert into city (city_id, name) values ('91906', 'Semerak');
insert into city (city_id, name) values ('94308', 'San Pedro');
insert into city (city_id, name) values ('36084', 'La Paz');
insert into city (city_id, name) values ('52238', 'Na Thawi');
